events {}

http {
    server {
        listen 80;
        return 301 https://localhost:8443$request_uri;
    }
    server {
        listen 443 ssl;
	
        ssl_certificate /etc/nginx/ssl/server.cert;
        ssl_certificate_key /etc/nginx/ssl/server.key;
        
        access_log syslog:server=host.docker.internal:514,facility=local0,tag=nginx;

        location / {
            proxy_pass http://flask:5000;

        }

    }

}
