---
- name: Configuration files
  hosts: webservers
  become: true

  tasks:
    - name: Install Required Tools
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose-v2
          - git
          - ufw
          - openssl
        state: present
        update_cache: true
    
    - name: Status Docker
      ansible.builtin.systemd_service:
        name: docker
        state: started
        enabled: true
    
    - name: Create workdir
      ansible.builtin.file:
        path: /opt/hebrew-study-school
        state: directory
        owner: wrag
        group: wrag 
    
    - name: Automate Git Pull
      ansible.builtin.git:
        repo: git@github.com:Alexandr5321/study_school_project.git
        dest: /opt/hebrew-study-school
        key_file: /home/wrag/.ssh/hebrew_study_school_ed25519
        update: true

    - name: Generate self-signed SSL certificate
      ansible.builtin.command:
        cmd: >
          openssl req -x509 -nodes -days 365
          -newkey rsa:2048
          -keyout /opt/hebrew-study-school/nginx/ssl/server.key
          -out /opt/hebrew-study-school/nginx/ssl/server.cert
          -subj "/CN=localhost"
        creates: /opt/hebrew-study-school/nginx/ssl/server.cert

    - name: Deploy application
      ansible.builtin.command:
        cmd: docker compose -f docker-compose-application.yml -p application up -d --build
        chdir: /opt/hebrew-study-school

    - name: Allow SSH
      community.general.ufw:
        rule: allow
        port: "22"
        src: "192.168.64.1"
        proto: tcp

    - name: Set UFW defaults
      community.general.ufw:
        direction: incoming
        policy: deny

    - name: Allow outgoing traffic
      community.general.ufw:
        direction: outgoing
        policy: allow

    - name: Enable UFW
      community.general.ufw:
        state: enabled

    - name: Deny Traffic
      community.general.ufw:
        direction: routed
        policy: deny
